name: ${project.name}
version: ${project.version}
description: ToBeNamed
authors: [aumgn, first4ever]
website: https://github.com/aumgn/ToBeNamed

main: fr.aumgn.tobenamed.TBNPlugin

commands:
    stop-game:
        description: "Stop la partie en cours."
        usage: "/<command>"
        permission: "tbn.cmd.stop"
        aliases: ["sg"]
    show-teams:
        description: "Affiche les équipes"
        usage: "/<command>"
        permission: "tbn.cmd.showteams"
        aliases: ["showteams", "st"]

    init-game:
        description: "Initie une partie de TBN."
        usage: "/<command> [-a] <equipe1> <equipe2> [...]"
        permission: "tbn.cmd.init"
        aliases: ["init"]
    join-team:
        description: "Rejoins (ou cree) une equipe."
        usage: "/<command> <equipe>"
        permission: "tbn.cmd.jointeam"
        aliases: ["jt", "join"]
    start-game:
        description: "Debute la partie."
        usage: "/<command>"
        permission: "tbn.cmd.start"
        aliases: ["start", "sg"]

    watch-game:
        description: "Inscris en tant que spectateur de la partie."
        usage: "/<command>"
        permission: "tbn.cmd.watch"
        aliases: ["watch", "spect-game", "spect"]
    unwatch-game:
        description: "Desinscris en tant que spectateur de la partie."
        usage: "/<command>"
        permission: "tbn.cmd.watch"
        aliases: ["unwatch", "unspect-game", "unspect"]
    teleport-player:
        description: "Teleporte a un joueur."
        usage: "/<command> <player>"
        permission: "tbn.cmd.tpplayer"
        aliases: ["tpp"]
    teleport-team:
        description: "Teleporte a un point strategique d'une equipe."
        usage: "/<command> [-fs] <team>"
        permission: "tbn.cmd.tpteam"
        aliases: ["tpt"]

permissions:
    tbn.manage:
        default: op
        children:
            tbn.cmd.stop: true
            tbn.cmd.init: true
            tbn.cmd.start: true
            tbn.play: true
    tbn.play:
        default: true
        children:
            tbn.cmd.jointeam: true
            tbn.cmd.showteams: true
    tbn.watch:
        default: true
        children:
            tbn.cmd.watch: true
            tbn.cmd.tpplayer: true
            tbn.cmd.tpteam: true
