name: ${project.name}
version: ${project.version}
description: DiamondRush
authors: [aumgn]
website: https://github.com/aumgn/DiamondRush

main: fr.aumgn.diamondrush.DiamondRushPlugin

commands:
    diamondrush:
        description: "Commande principale"
        usage: "init | join | start | quit | pause | resume | teams | watch | unwatch | tp-player | tp-team"
        aliases: ["dr"]

    "diamondrush reload":
        description: "Recharge la configuration."
        usage: ""
        aliases: ["rl"]
        permission: "dr.cmd.reload"

    "diamondrush stop":
        description: "Stoppe la partie en cours."
        usage: ""
        permission: "dr.cmd.stop"
    "diamondrush pause":
        description: "Met en pause la partie en cours."
        usage: ""
        aliases: ["pause"]
        permission: "dr.cmd.stop"
    "diamondrush resume":
        description: "Redémarre la partie."
        usage: ""
        aliases: ["resume", "rsm"]
        permission: "dr.cmd.stop"

    "diamondrush teams":
        description: "Affiche les équipes"
        usage: ""
        permission: "dr.cmd.showteams"
        aliases: ["st"]
    "diamondrush spectators":
        description: "Affiche la liste des spectateurs."
        usage: ""
        permission: "dr.cmd.spectators"
        aliases: ["spectators"]
    "diamondrush stats":
        description: "Affiche les statistiques d'un joueur."
        usage: "<player>"
        permission: "dr.cmd.stats"
        aliases: ["stats"]

    "diamondrush init":
        description: "Initie une partie de Diamond Rush."
        usage: "[-a] <equipe1> <equipe2> [...]"
        permission: "dr.cmd.init"
        aliases: ["init"]
    "diamondrush join":
        description: "Rejoint (ou crée) une équipe."
        usage: "[equipe]"
        permission: "dr.cmd.join"
        aliases: ["join"]
    "diamondrush quit":
        description: "Quitte la partie."
        usage: ""
        permission: "dr.cmd.quit"
        aliases: ["quit"]
    "diamondrush start":
        description: "Débute la partie."
        usage: ""
        permission: "dr.cmd.start"
        aliases: ["start"]

    "diamondrush watch":
        description: "Inscrit en tant que spectateur de la partie."
        usage: ""
        permission: "dr.cmd.watch"
        aliases: ["watch", "spect"]
    "diamondrush unwatch":
        description: "Désinscrit en tant que spectateur de la partie."
        usage: ""
        permission: "dr.cmd.unwatch"
        aliases: ["unwatch", "unspect"]
    "diamondrush tp-player":
        description: "Téléporte à un joueur."
        usage: "<player>"
        permission: "dr.cmd.tpplayer"
        aliases: ["tpp"]
    "diamondrush tp-team":
        description: "Téléporte à un point stratégique d'une équipe."
        usage: "[-fs] <team>"
        permission: "dr.cmd.tpteam"
        aliases: ["tpt"]
    "diamondrush inventory":
        description: "Ouvre l'inventaire d'un joueur."
        usage: "<player>"
        permission: "dr.cmd.inventory"
        aliases: ["inv"]

permissions:
    "dr.*":
        default: false
        children:
            dr.admin: true
    dr.admin:
        default: op
        children:
            dr.cmd.reload: true
            dr.manage: true
    dr.manage:
        default: false
        children:
            dr.cmd.stop: true
            dr.cmd.init: true
            dr.cmd.start: true
            dr.cmd.quit: true
            dr.cmd.quit.others: true
            dr.cmd.unwatch: true
            dr.cmd.unwatch.others: true
            dr.play: true
            dr.watch: true
    dr.play:
        default: true
        children:
            dr.cmd.jointeam: true
            dr.cmd.showteams: true
            dr.cmd.spectators: true
            dr.cmd.stats: true
    dr.watch:
        default: true
        children:
            dr.cmd.watch: true
            dr.cmd.tpplayer: true
            dr.cmd.tpteam: true
            dr.cmd.inventory: true
