name: ${project.name}
version: ${project.version}
description: ToBeNamed
authors: [aumgn, first4ever]
website: https://github.com/aumgn/ToBeNamed

main: fr.aumgn.tobenamed.TBNPlugin

commands:
    show-teams:
        description: "Affiche les équipes"
        usage: "/<command>"
        aliases: ["showteams", "st"]

    init-game:
        description: "Initie une partie de TBN."
        usage: "/<command> [-a] <equipe1> <equipe2> [...]"
        permission: "tbn.cmd.init"
        aliases: ["init"]
    join-team:
        description: "Rejoins (ou cree) une equipe."
        usage: "/<command> <equipe>"
        permission: "tbn.cmd.jointeam"
        aliases: ["jt", "join"]
    start-game:
        description: "Debute la partie."
        usage: "/<command>"
        aliases: ["start", "sg"]

    watch-game:
        description: "S'inscrire en tant que spectateur de la partie."
        usage: "/<command>"
        permission: "tbn.cmd.watch"
        aliases: ["watch", "spect-game", "spect"]
    unwatch-game:
        description: "Se desinscrire en tant que spectateur de la partie."
        usage: "/<command>"
        permission: "tbn.cmd.watch"
        aliases: ["unwatch", "unspect-game", "unspect"]
    teleport-player:
        description: "Teleporte a un joueur."
        usage: "/<command> <player>"
        permission: "tbn.cmd.tpplayer"
        aliases: ["tpp"]
    teleport-team:
        description: "Teleporte a un point strategique d'une equipe."
        usage: "/<command> [-fs] <team>"
        permission: "tbn.cmd.tpteam"
        aliases: ["tpt"]

