name: ${project.name}
version: ${project.version}
description: DiamondRush
authors: [aumgn]
website: https://github.com/aumgn/DiamondRush

main: fr.aumgn.diamondrush.DiamondRushPlugin

commands:
    diamondrush:
        description: "Commande principale"
        usage: "init | join | start | quit | pause | resume | teams | watch | unwatch | tp-player | tp-team"
        aliases: ["dr"]
    "diamondrush stop":
        description: "Stoppe la partie en cours."
        usage: ""
        permission: "dr.cmd.stop"
    "diamondrush pause":
        description: "Met en pause la partie en cours."
        usage: ""
        aliases: ["pause"]
        permission: "dr.cmd.stop"
    "diamondrush resume":
        description: "Redémarre la partie."
        usage: ""
        aliases: ["resume", "rsm"]
        permission: "dr.cmd.stop"
    "diamondrush teams":
        description: "Affiche les équipes"
        usage: ""
        permission: "dr.cmd.showteams"
        aliases: ["st"]

    "diamondrush init":
        description: "Initie une partie de TBN."
        usage: "[-a] <equipe1> <equipe2> [...]"
        permission: "dr.cmd.init"
        aliases: ["init"]
    "diamondrush join":
        description: "Rejoint (ou crée) une équipe."
        usage: "[equipe]"
        permission: "dr.cmd.jointeam"
        aliases: ["join"]
    "diamondrush quit":
        description: "Quitte la partie."
        usage: ""
        permission: "dr.cmd.jointeam"
        aliases: ["quit"]
    "diamondrush start":
        description: "Débute la partie."
        usage: ""
        permission: "dr.cmd.start"
        aliases: ["start"]

    "diamondrush watch":
        description: "Inscrit en tant que spectateur de la partie."
        usage: ""
        permission: "dr.cmd.watch"
        aliases: ["watch", "spect"]
    "diamondrush unwatch":
        description: "Désinscrit en tant que spectateur de la partie."
        usage: ""
        permission: "dr.cmd.watch"
        aliases: ["unwatch", "unspect"]
    "diamondrush tp-player":
        description: "Téléporte à un joueur."
        usage: "<player>"
        permission: "dr.cmd.tpplayer"
        aliases: ["tpp"]
    "diamondrush tp-team":
        description: "Téléporte à un point stratégique d'une équipe."
        usage: "[-fs] <team>"
        permission: "dr.cmd.tpteam"
        aliases: ["tpt"]

permissions:
    dr.manage:
        default: op
        children:
            dr.cmd.stop: true
            dr.cmd.init: true
            dr.cmd.start: true
            dr.play: true
    dr.play:
        default: true
        children:
            dr.cmd.jointeam: true
            dr.cmd.showteams: true
    dr.watch:
        default: true
        children:
            dr.cmd.watch: true
            dr.cmd.tpplayer: true
            dr.cmd.tpteam: true
